name: flutter_graphql
description: A GraphQL client for Flutter, bringing all the features from a modern GraphQL client to one easy to use package.
version: 1.1.4-dev.5
homepage: https://github.com/snowballdigital/graphql-flutter/tree/master

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  http_parser: ^4.0.0
  path_provider: ^2.0.5
  uuid: ^3.0.5
  sqflite: ^2.0.0+4
  graphql_parser2: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
